<?php
// data.php — LakbayLokal Unified Data
// Single source of truth for destinations, hotels, and activities.

$destinations = [
  [
    'id' => 'baguio', 'name' => 'Baguio City', 'region' => 'Luzon', 'price' => 4500,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(109,177,197,0.75), rgba(0,0,0,0.22)), url('assets/pics/Baguio.jpg') center/cover no-repeat",
    'tagline' => 'The Summer Capital of the Philippines',
    'desc' => 'Escape to the cool mountain air of Baguio City and discover pine forests, strawberry farms, and rich Igorot culture.',
    'activities' => ['Strawberry Farms', 'Adventure Park', 'Museums'],
    'price_from' => 2800,
    'hotels' => [
      [
        'id' => 'sotogrande-baguio',
        'name' => 'Sotogrande Hotel Baguio',
        'image' => 'assets/pics/sotogrande.jpg',
        'stars' => 4, 'price' => 5200, 'rating' => 4.6, 'reviews' => 312,
        'location' => 'Session Road, Baguio City',
        'desc' => 'A modern boutique hotel nestled in the heart of Baguio, offering luxurious rooms with stunning mountain views and world-class amenities.',
        'amenities' => ['Free WiFi', 'Restaurant', 'Pool', 'Gym', 'Parking', 'Room Service'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Government-issued ID required', 'No pets allowed', 'Extra person charges apply'],
      ],
      [
        'id' => 'microtel-baguio',
        'name' => 'Microtel by Wyndham Baguio',
        'image' => 'assets/pics/microtel3.jpg',
        'stars' => 3, 'price' => 3600, 'rating' => 4.3, 'reviews' => 205,
        'location' => 'Legarda Road, Baguio City',
        'desc' => 'Comfortable and affordable rooms with reliable service, conveniently located near SM City Baguio and key tourist spots.',
        'amenities' => ['Free WiFi', 'Breakfast', 'Parking', 'Room Service', 'Laundry'],
        'checkin' => '14:00', 'checkout' => '12:00',
        'policies' => ['Check-in age: 18+', 'Cash or card accepted', 'Cancellation: 24hrs prior'],
      ],
      [
        'id' => 'travelite-baguio',
        'name' => 'Travelite Express Hotel',
        'image' => 'assets/pics/travellite2.jpg',
        'stars' => 2, 'price' => 2800, 'rating' => 4.1, 'reviews' => 148,
        'location' => 'Magsaysay Avenue, Baguio City',
        'desc' => 'A budget-friendly option with clean, cozy rooms ideal for solo travelers and backpackers exploring the City of Pines.',
        'amenities' => ['Free WiFi', 'Air Conditioning', '24/7 Front Desk'],
        'checkin' => '13:00', 'checkout' => '11:00',
        'policies' => ['No smoking in rooms', 'Quiet hours: 10PM–7AM'],
      ],
    ],
    'acts' => [
      ['name' => 'Strawberry Picking at La Trinidad Farm', 'price' => 250],
      ['name' => 'BenCab Museum Gallery Tour',             'price' => 200],
      ['name' => 'Tree Top Adventure – Camp John Hay',     'price' => 400],
      ['name' => 'Igorot Stone Kingdom Exploration',       'price' => 150],
    ],
  ],
  [
    'id' => 'vigan', 'name' => 'Vigan City', 'region' => 'Luzon', 'price' => 6500,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.34), rgba(0,0,0,0.05)), url('assets/pics/vigan.jpg') center/cover no-repeat",
    'tagline' => 'UNESCO World Heritage City',
    'desc' => 'Walk the cobblestone streets of a colonial-era city frozen in time, with kalesas, ancestral houses, and Ilocano cuisine.',
    'activities' => ['Heritage Walk', 'Pottery', 'Calesa Ride'],
    'price_from' => 3500,
    'hotels' => [
      [
        'id' => 'hotel-luna-vigan',
        'name' => 'Hotel Luna',
        'image' => 'assets/pics/hotelluna2.jpg',
        'stars' => 4, 'price' => 5800, 'rating' => 4.8, 'reviews' => 421,
        'location' => 'Crisologo St., Vigan City',
        'desc' => 'An award-winning boutique hotel housed in a century-old ancestral mansion, blending heritage architecture with modern luxury on the famous Calle Crisologo.',
        'amenities' => ['Free WiFi', 'Rooftop Pool', 'Art Gallery', 'Restaurant', 'Room Service', 'Concierge'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Government-issued ID required', 'No pets allowed', 'Cancellation: 48hrs prior'],
      ],
      [
        'id' => 'hotel-felicidad',
        'name' => 'Hotel Felicidad Vigan',
        'image' => 'assets/pics/hotelfelicidad2.jpg',
        'stars' => 3, 'price' => 4200, 'rating' => 4.4, 'reviews' => 186,
        'location' => 'Quirino Blvd, Vigan City',
        'desc' => 'A charming heritage hotel offering comfortable rooms with period-inspired décor, located steps away from Vigan\'s famous plazas and churches.',
        'amenities' => ['Free WiFi', 'Breakfast Included', 'Parking', 'Tour Desk'],
        'checkin' => '14:00', 'checkout' => '12:00',
        'policies' => ['Breakfast served 6AM–9AM', 'Extra bed available on request'],
      ],
      [
        'id' => 'paradores-vigan',
        'name' => 'Paradores de Vigan',
        'image' => 'assets/pics/paradores de.jpg',
        'stars' => 3, 'price' => 3500, 'rating' => 4.2, 'reviews' => 97,
        'location' => 'Mena Crisologo St., Vigan City',
        'desc' => 'Experience the warmth of Ilocano hospitality in this cozy, family-run hotel set in a restored colonial building within the heritage zone.',
        'amenities' => ['Free WiFi', 'Courtyard Garden', 'Bike Rental', 'Breakfast'],
        'checkin' => '13:00', 'checkout' => '11:00',
        'policies' => ['No pets', 'Cash payment preferred', 'Early check-in subject to availability'],
      ],
    ],
    'acts' => [
      ['name' => 'Calesa Ride around Calle Crisologo',      'price' => 250],
      ['name' => 'Pagburnayan Jar Factory Pottery Making',  'price' => 300],
      ['name' => 'Vigan Museum / Syquia Mansion Tour',      'price' => 180],
    ],
  ],
  [
    'id' => 'palawan', 'name' => 'Palawan', 'region' => 'Luzon', 'price' => 8500,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.28), rgba(0,0,0,0.1)), url('assets/pics/palawan.jpg') center/cover no-repeat",
    'tagline' => 'Last Frontier of the Philippines',
    'desc' => 'Crystal lagoons, secret beaches, WWII shipwrecks, and the world-famous Underground River await in paradise Palawan.',
    'activities' => ['Lagoon Tours', 'Underground River', 'Diving'],
    'price_from' => 6500,
    'hotels' => [
      [
        'id' => 'seda-lio',
        'name' => 'Seda Lio – El Nido',
        'image' => 'assets/pics/sedalio2.jpg',
        'stars' => 5, 'price' => 12500, 'rating' => 4.9, 'reviews' => 534,
        'location' => 'Lio Tourism Estate, El Nido, Palawan',
        'desc' => 'A stunning eco-luxury resort set on the shores of El Nido\'s Lio Beach, offering sustainable luxury with panoramic views of the Bacuit Archipelago.',
        'amenities' => ['Infinity Pool', 'Beach Access', 'Spa', 'Restaurant', 'Water Sports', 'Free WiFi'],
        'checkin' => '15:00', 'checkout' => '12:00',
        'policies' => ['Adults only: 18+', 'No outside food/drinks', 'Strictly no smoking'],
      ],
      [
        'id' => 'hue-hotels-pp',
        'name' => 'Hue Hotels – Puerto Princesa',
        'image' => 'assets/pics/huehotel2.jpg',
        'stars' => 4, 'price' => 7200, 'rating' => 4.6, 'reviews' => 298,
        'location' => 'Rizal Avenue, Puerto Princesa City',
        'desc' => 'A vibrant, design-forward hotel in the heart of Puerto Princesa, offering colorful rooms, an excellent restaurant, and easy access to the city\'s attractions.',
        'amenities' => ['Pool', 'Restaurant', 'Free WiFi', 'Gym', 'Airport Shuttle', 'Kids Club'],
        'checkin' => '14:00', 'checkout' => '12:00',
        'policies' => ['Children under 12 stay free', 'Credit cards accepted', 'Tour desk available'],
      ],
      [
        'id' => 'two-seasons-coron',
        'name' => 'Two Seasons Coron Island Resort',
        'image' => 'assets/pics/two seasons.jpg',
        'stars' => 4, 'price' => 9800, 'rating' => 4.7, 'reviews' => 187,
        'location' => 'Malaroyroy Peninsula, Coron, Palawan',
        'desc' => 'Perched on a private peninsula overlooking the famous Coron Bay, this overwater resort offers an intimate island experience with world-class diving access.',
        'amenities' => ['Overwater Villas', 'Dive Center', 'Kayaking', 'Restaurant', 'Snorkeling Gear', 'Free WiFi'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Minimum stay: 2 nights', 'Dive packages available', 'Airport transfer included'],
      ],
    ],
    'acts' => [
      ['name' => 'El Nido Tour A – Lagoons & Islands',       'price' => 1200],
      ['name' => 'Puerto Princesa Underground River Tour',   'price' => 2750],
      ['name' => 'Coron Shipwreck & Snorkeling Tour',        'price' => 1600],
      ['name' => 'Wildlife Safari at Calauit Sanctuary',     'price' => 2500],
    ],
  ],
  [
    'id' => 'cebu', 'name' => 'Cebu City', 'region' => 'Visayas', 'price' => 5500,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.32), rgba(0,0,0,0.08)), url('assets/pics/Cebu2.jpg') center/cover no-repeat",
    'tagline' => 'The Queen City of the South',
    'desc' => 'From canyoneering in Kawasan Falls to swimming with whale sharks in Oslob — Cebu offers it all.',
    'activities' => ['Canyoneering', 'Whale Sharks', 'Temple'],
    'price_from' => 3200,
    'hotels' => [
      [
        'id' => 'radisson-blu-cebu',
        'name' => 'Radisson Blu Cebu',
        'image' => 'assets/pics/radisson.jpg',
        'stars' => 5, 'price' => 9500, 'rating' => 4.7, 'reviews' => 689,
        'location' => 'Sergio Osmeña Blvd, Cebu City',
        'desc' => 'A five-star landmark in the heart of Cebu City, offering elegant rooms, multiple dining venues, a rooftop pool, and a world-class spa.',
        'amenities' => ['Rooftop Pool', 'Spa', 'Multiple Restaurants', 'Free WiFi', 'Business Center', 'Gym'],
        'checkin' => '15:00', 'checkout' => '12:00',
        'policies' => ['Government-issued ID required', 'Check-in age: 18+', 'Pets not allowed'],
      ],
      [
        'id' => 'quest-hotel-cebu',
        'name' => 'Quest Hotel Cebu',
        'image' => 'assets/pics/questhotel.jpg',
        'stars' => 4, 'price' => 5500, 'rating' => 4.4, 'reviews' => 412,
        'location' => 'Archbishop Reyes Ave, Cebu City',
        'desc' => 'A contemporary hotel known for its vibrant social spaces, spectacular pool area, and easy access to Cebu\'s business and leisure districts.',
        'amenities' => ['Pool', 'Free WiFi', 'Restaurant', 'Gym', 'Parking', 'Event Halls'],
        'checkin' => '14:00', 'checkout' => '12:00',
        'policies' => ['Children welcome', 'Cancellation: 24hrs prior', 'Airport shuttle available'],
      ],
      [
        'id' => 'bayfront-cebu',
        'name' => 'Bayfront Hotel Cebu',
        'image' => 'assets/pics/bayfront.jpg',
        'stars' => 3, 'price' => 3200, 'rating' => 4.2, 'reviews' => 253,
        'location' => 'Manalili St, Cebu City',
        'desc' => 'A reliable mid-range option in Cebu City offering clean, comfortable rooms with great city views and close proximity to Carbon Market and Colon Street.',
        'amenities' => ['Free WiFi', 'Air Conditioning', 'Restaurant', '24/7 Front Desk', 'Laundry Service'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['No pets', 'Cash or card', 'Quiet hours: 11PM'],
      ],
    ],
    'acts' => [
      ['name' => 'Kawasan Falls Canyoneering',   'price' => 1500],
      ['name' => 'Temple of Leah Tour',          'price' => 100],
      ['name' => 'Oslob Whale Shark Watching',   'price' => 500],
    ],
  ],
  [
    'id' => 'boracay', 'name' => 'Boracay Island', 'region' => 'Visayas', 'price' => 7500,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.22), rgba(0,0,0,0.08)), url('assets/pics/boracay.jpg') center/cover no-repeat",
    'tagline' => 'World-Famous White Sand Beach',
    'desc' => "Powdery white sand, turquoise waters, and endless island adventures — Boracay is the Philippines' crown jewel.",
    'activities' => ['Island Hopping', 'Parasailing', 'Diving'],
    'price_from' => 5500,
    'hotels' => [
      [
        'id' => 'henann-crystal',
        'name' => 'Henann Crystal Sands Resort',
        'image' => 'assets/pics/boracay.jpg',
        'stars' => 5, 'price' => 11800, 'rating' => 4.8, 'reviews' => 876,
        'location' => 'Station 1, White Beach, Boracay',
        'desc' => 'An iconic beachfront resort on the finest stretch of White Beach, offering breathtaking sunsets, multiple pools, and world-class island dining.',
        'amenities' => ['Beachfront', '3 Pools', 'Water Sports', 'Multiple Restaurants', 'Spa', 'Free WiFi'],
        'checkin' => '14:00', 'checkout' => '12:00',
        'policies' => ['No day-tour guests', 'Minimum age for alcohol: 18+', 'Beach access 24/7'],
      ],
      [
        'id' => 'fairways-boracay',
        'name' => 'Fairways and Bluewater Boracay',
        'image' => 'assets/pics/boracay.jpg',
        'stars' => 5, 'price' => 14500, 'rating' => 4.9, 'reviews' => 432,
        'location' => 'Newcoast, Boracay Island',
        'desc' => "Boracay's only golf resort, offering sprawling tropical villas, championship fairways, and direct access to a pristine private beach.",
        'amenities' => ['Golf Course', 'Private Beach', 'Spa', 'Multiple Pools', 'Tennis', 'Free WiFi'],
        'checkin' => '15:00', 'checkout' => '12:00',
        'policies' => ['Shuttle to White Beach available', 'Golf rounds bookable in advance', 'Pets not allowed'],
      ],
      [
        'id' => 'la-carmela-boracay',
        'name' => 'La Carmela de Boracay',
        'image' => 'assets/pics/boracay.jpg',
        'stars' => 3, 'price' => 5500, 'rating' => 4.2, 'reviews' => 321,
        'location' => 'Station 2, White Beach, Boracay',
        'desc' => 'A charming resort right on White Beach, offering great value with comfortable rooms and the convenience of beachfront access at Station 2.',
        'amenities' => ['Beachfront Location', 'Restaurant', 'Free WiFi', 'Room Service', 'Tour Desk'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Early check-in subject to availability', 'No outside alcohol on the beach', 'Cash & card accepted'],
      ],
    ],
    'acts' => [
      ['name' => 'Island Hopping Tour',  'price' => 800],
      ['name' => 'Parasailing Activity', 'price' => 2000],
      ['name' => 'Helmet Diving',        'price' => 700],
    ],
  ],
  [
    'id' => 'siargao', 'name' => 'Siargao Island', 'region' => 'Mindanao', 'price' => 3700,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.32), rgba(0,0,0,0.08)), url('assets/pics/siargao.jpg') center/cover no-repeat",
    'tagline' => 'Surfing Capital of the Philippines',
    'desc' => "Ride the world-famous Cloud 9 waves, hop between pristine islands, and soak in Siargao's laid-back surf culture.",
    'activities' => ['Surfing', 'Island Hopping', 'Bike Rides'],
    'price_from' => 3700,
    'hotels' => [
      [
        'id' => 'nay-palad-siargao',
        'name' => 'Nay Palad Hideaway',
        'image' => 'assets/pics/siargao.jpg',
        'stars' => 5, 'price' => 18000, 'rating' => 4.9, 'reviews' => 156,
        'location' => 'Pacifico, Siargao Island',
        'desc' => "An ultra-exclusive eco-luxury hideaway on Siargao's wild northern shore, offering just 10 private beachfront cottages with personalized butler service.",
        'amenities' => ['Private Beach', 'Infinity Pool', 'Organic Restaurant', 'Surfing Access', 'Spa', 'Butler Service'],
        'checkin' => '15:00', 'checkout' => '12:00',
        'policies' => ['Adults only: 12+', 'All-inclusive available', 'Advance booking required'],
      ],
      [
        'id' => 'kalinaw-siargao',
        'name' => 'Kalinaw Resort',
        'image' => 'assets/pics/siargao.jpg',
        'stars' => 4, 'price' => 7500, 'rating' => 4.7, 'reviews' => 289,
        'location' => 'General Luna, Siargao Island',
        'desc' => 'A tranquil boutique resort tucked among coconut palms near Cloud 9, offering stunning lagoon views and a genuine island atmosphere.',
        'amenities' => ['Lagoon Views', 'Pool', 'Restaurant', 'Surf Board Rental', 'Free WiFi', 'Bicycle Rental'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Minimum 2-night stay on weekends', 'No children under 10', 'Cashless payment only'],
      ],
      [
        'id' => 'villa-cali-siargao',
        'name' => 'Villa Cali',
        'image' => 'assets/pics/siargao.jpg',
        'stars' => 3, 'price' => 3700, 'rating' => 4.3, 'reviews' => 198,
        'location' => 'General Luna, Siargao Island',
        'desc' => 'A laid-back villa perfect for surf enthusiasts and budget travelers, with cozy rooms, a social common area, and walking distance to Cloud 9 breaks.',
        'amenities' => ['Free WiFi', 'Surfboard Storage', 'Common Area', 'Hammock Garden', 'Breakfast Available'],
        'checkin' => '13:00', 'checkout' => '11:00',
        'policies' => ['Cash only', 'No pets', 'Communal areas shared'],
      ],
    ],
    'acts' => [
      ['name' => 'Island Hopping',            'price' => 2500],
      ['name' => 'Basic Surf Lesson',          'price' => 700],
      ['name' => 'Motorbike Rental (per day)', 'price' => 500],
    ],
  ],
  [
    'id' => 'bukidnon', 'name' => 'Bukidnon', 'region' => 'Mindanao', 'price' => 2100,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.28), rgba(0,0,0,0.06)), url('assets/pics/bukidno.jpg') center/cover no-repeat",
    'tagline' => 'Thrills at Dahilayan Adventure Park',
    'desc' => "Experience the longest zipline in Asia, ATV rides through highland meadows, and the cool breeze of Mindanao's highlands.",
    'activities' => ['Zipline', 'ATV', 'DropZone'],
    'price_from' => 2100,
    'hotels' => [
      [
        'id' => 'dahilayan-resort',
        'name' => 'Dahilayan Forest Park Resort',
        'image' => 'assets/pics/bukidno.jpg',
        'stars' => 4, 'price' => 4500, 'rating' => 4.5, 'reviews' => 312,
        'location' => 'Dahilayan, Manolo Fortich, Bukidnon',
        'desc' => 'Stay right at the adventure park and wake up to misty mountain views. Direct access to all zipline and extreme adventure facilities.',
        'amenities' => ['Free WiFi', 'Restaurant', 'Adventure Park Access', 'Parking', 'Room Service'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Government-issued ID required', 'No pets', 'Height restrictions apply for some activities'],
      ],
      [
        'id' => 'ultrawinds-resort',
        'name' => 'Ultrawinds Mountain Resort',
        'image' => 'assets/pics/bukidno.jpg',
        'stars' => 3, 'price' => 3200, 'rating' => 4.3, 'reviews' => 198,
        'location' => 'Manolo Fortich, Bukidnon',
        'desc' => 'A scenic highland resort with comfortable accommodations and stunning views of Bukidnon\'s pine-covered mountains.',
        'amenities' => ['Free WiFi', 'Restaurant', 'Mountain View', 'Parking', 'Bonfire Area'],
        'checkin' => '13:00', 'checkout' => '11:00',
        'policies' => ['Cash payment preferred', 'Group rates available', 'Quiet hours: 10PM'],
      ],
      [
        'id' => 'secret-haven-bukidnon',
        'name' => 'Secret Haven Private Resort',
        'image' => 'assets/pics/bukidno.jpg',
        'stars' => 3, 'price' => 2100, 'rating' => 4.1, 'reviews' => 145,
        'location' => 'Bukidnon Province',
        'desc' => 'An intimate private resort surrounded by nature, perfect for group getaways with exclusive use of the property.',
        'amenities' => ['Pool', 'Free WiFi', 'BBQ Area', 'Exclusive Use', 'Kitchen Facilities'],
        'checkin' => '13:00', 'checkout' => '11:00',
        'policies' => ['Private booking required', 'Outside food allowed', 'No overnight pets'],
      ],
    ],
    'acts' => [
      ['name' => 'ATV – Dahilayan Adventure Park',        'price' => 850],
      ['name' => '840m Zipline – Dahilayan Adventure Park','price' => 500],
      ['name' => 'DropZone – Dahilayan Adventure Park',   'price' => 500],
      ['name' => 'ZipKart – Dahilayan Adventure Park',    'price' => 250],
    ],
  ],
  [
    'id' => 'camiguin', 'name' => 'Camiguin Island', 'region' => 'Mindanao', 'price' => 7500,
    'emoji' => '',
    'gradient' => "linear-gradient(135deg, rgba(0,0,0,0.32), rgba(0,0,0,0.08)), url('assets/pics/camiguin.jpg') center/cover no-repeat",
    'tagline' => 'Island Born of Fire',
    'desc' => 'This tiny island has more volcanoes per square kilometer than anywhere on Earth, plus stunning waterfalls and turquoise springs.',
    'activities' => ['Island Hopping', 'Waterfalls', 'Diving'],
    'price_from' => 3500,
    'hotels' => [
      [
        'id' => 'bintana-paraiso',
        'name' => 'Bintana sa Paraiso',
        'image' => 'assets/pics/camiguin.jpg',
        'stars' => 4, 'price' => 5800, 'rating' => 4.7, 'reviews' => 203,
        'location' => 'Mambajao, Camiguin Island',
        'desc' => 'A picturesque resort with sea-facing cottages and direct beach access, offering a genuine island paradise experience in Camiguin.',
        'amenities' => ['Beach Access', 'Restaurant', 'Free WiFi', 'Snorkeling Gear', 'Tour Desk', 'Kayaking'],
        'checkin' => '14:00', 'checkout' => '11:00',
        'policies' => ['Government-issued ID required', 'Cash or card accepted', 'Dive packages available'],
      ],
      [
        'id' => 'paras-beach',
        'name' => 'Paras Beach Resort',
        'image' => 'assets/pics/camiguin.jpg',
        'stars' => 3, 'price' => 4200, 'rating' => 4.4, 'reviews' => 178,
        'location' => 'Guinsiliban, Camiguin Island',
        'desc' => 'A beloved beachside resort known for its warm hospitality, well-kept grounds, and stunning views of the island\'s volcanic peaks.',
        'amenities' => ['Beachfront', 'Restaurant', 'Free WiFi', 'Pool', 'Outdoor Bar'],
        'checkin' => '14:00', 'checkout' => '12:00',
        'policies' => ['No pets', 'Early check-in on request', 'Cash payment preferred'],
      ],
      [
        'id' => 'balai-baibai',
        'name' => 'Balai sa Baibai',
        'image' => 'assets/pics/camiguin.jpg',
        'stars' => 3, 'price' => 3500, 'rating' => 4.2, 'reviews' => 134,
        'location' => 'Mambajao, Camiguin Island',
        'desc' => 'A cozy family-run beachside inn offering affordable comfort and genuine Camiguinon hospitality just steps from the beach.',
        'amenities' => ['Free WiFi', 'Beach Access', 'Breakfast Available', 'Communal Kitchen', 'Hammocks'],
        'checkin' => '13:00', 'checkout' => '11:00',
        'policies' => ['Cash only', 'Breakfast not included (available for fee)', 'No smoking in rooms'],
      ],
    ],
    'acts' => [
      ['name' => 'Island Hopping',  'price' => 2500],
      ['name' => 'Waterfalls Tour', 'price' => 3500],
      ['name' => 'Scuba Diving',    'price' => 2800],
    ],
  ],
];

// ── Helper functions ──────────────────────────────────────────

function getDestById(string $id): ?array {
  global $destinations;
  foreach ($destinations as $d) {
    if ($d['id'] === $id) return $d;
  }
  return null;
}

function getHotelById(string $destId, string $hotelId): ?array {
  $dest = getDestById($destId);
  if (!$dest) return null;
  foreach ($dest['hotels'] as $h) {
    if ($h['id'] === $hotelId) return $h;
  }
  return null;
}
